require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 3.1.2
  TargetRailsVersion: 7.0.3
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'test/**/*'
Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
Lint/AmbiguousBlockAssociation, RSpec/MultipleExpectations:
  Exclude:
    - spec/**/*
RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/**/*
Documentation:
    Enabled: false