version: "3.8"
services:
  db:
    image: postgres:13-alpine
    command: ["postgres", "-c", "fsync=false", "-c", "full_page_writes=off"]
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: ./docker/app/app.Dockerfile
    command: bash -c "bundle exec puma -C config/puma.rb"
    volumes:
      - .:/app
    environment:
      DB_HOST: db
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: ./docker/web/nginx.Dockerfile
    depends_on:
      - app
    ports:
      - 80:80